version: '3.3'
services:
  nacos:
    image: nacos/nacos-server:v2.1.1
    container_name: nacos
    ports:
      - 8848:8848
      - 8849:8849
      - 9848:9848
      - 9849:9849
    restart: always
    privileged: true
    
    environment:
      - MODE=standalone
    volumes:
      - ./nacos-conf/application.properties:/home/nacos/conf/application.properties
      - ./nacos-logs:/home/nacos/logs
    links:
      - nacos-mysql
  nacos-mysql:
    container_name: nacos-mysql
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=000000
    ports:
      - "3306:3306"
